### ISSUE TITLE
Some suggestions for gitignore so that the codebase is clean

### ISSUE THREAD

**Issue by itsWindows11** [Microsoft-community/Dotsimus-TS#2]
As far as I know some files do not need to be included in GitHub such as:

- [x] Remove package-lock.json
- [ ] Remove yarn.lock

**Comment by cadenkoj** [comment]
Top 2 done in my PR, keeping .prettierrc,json because I assume it will be used in the future and the .vscode folder contains a launch configuration which should be left untouched for other VSCode users who like to use "Run and Debug"

**Comment by heftymouse** [comment]
.prettierrc should definitely be kept for future contributators so that everyone follows a common code style
perhaps even add https://github.com/marketplace/restyled-io/

**Comment by itsWindows11** [comment]
> Top 2 done in my PR, keeping .prettierrc,json because I assume it will be used in the future and the .vscode folder contains a launch configuration which should be left untouched for other VSCode users who like to use "Run and Debug"

Thanks, I've marked them as done, also I suggested one change in your PR

**Comment by cadenkoj** [comment]
Alright

**Comment by BeakerThe1st** [comment]
https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/
https://stackoverflow.com/questions/39990017/should-i-commit-the-yarn-lock-file-and-what-is-it-for
https://newbedev.com/should-i-commit-the-yarn-lock-file-and-what-is-it-for

I think we should keep yarn.lock 😄
